### ISSUE TITLE
Can't run "pod install"

### ISSUE THREAD

**Issue by maritovargass** [BlueSenseNetworks/iOS#1]
Hi, i'm trying to make the proper building and it gives me several error. First it tells me it can't find Campaign Demo.xcodeproj, then it tells me it can't find Campaing Demo target. 

Thanks

**Comment by vpetroff** [comment]
Hi, which project are you trying to build?

**Comment by maritovargass** [comment]
I'm trying to build campaign demo.

**Comment by vpetroff** [comment]
Hi, 

Please do a fresh pull from the repo. We have done some changes and refreshed both the SDK and the Campaign Demo sample (now called ProximitySense Campaign Demo).

**Comment by maritovargass** [comment]
Hi Vlad, just for let you know, users could face problems with the folder naming convention, for example in terminal if I do cd Campaign Demo it would tell me there's no folder with that name. I suggest Campaign-Demo or using - when having space in names. It's just a little detail.
